package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Book;
import vn.com.vti.springexam.entity.BookExample;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    int insert(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    int insertSelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    int updateByExampleSelective(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Oct 05 13:20:59 JST 2024
     */
    int updateByExample(@Param("row") Book row, @Param("example") BookExample example);
}